# https://github.com/sainnhe/everforest/blob/master/palette.md
# palette 1
bg_dim=#f2efdf
bg0=#fffbef
bg1=#f8f5e4
bg2=#f2efdf
bg3=#edeada
bg4=#e8e5d5
bg5=#bec5b2
bg_visual=#f0f2d4
bg_red=#ffe7de
bg_green=#f3f5d9
bg_blue=#ecf5ed
bg_yellow=#fef2d5
# palette 2
fg=#5c6a72
red=#f85552
orange=#f57d26
yellow=#dfa000
green=#8da101
aqua=#35a77c
blue=#3a94c5
purple=#df69ba
grey0=#a6b0a0
grey1=#939f91
grey2=#829181
statusline1=#93b259
statusline2=#708089
statusline3=#e66868
