# https://github.com/sainnhe/everforest/blob/master/palette.md
# palette 1
bg_dim=#e5dfc5
bg0=#f3ead3
bg1=#eae4ca
bg2=#e5dfc5
bg3=#ddd8be
bg4=#d8d3ba
bg5=#b9c0ab
bg_visual=#e1e4bd
bg_red=#f4dbd0
bg_green=#e5e6c5
bg_blue=#e1e7dd
bg_yellow=#f1e4c5
# palette 2
fg=#5c6a72
red=#f85552
orange=#f57d26
yellow=#dfa000
green=#8da101
aqua=#35a77c
blue=#3a94c5
purple=#df69ba
grey0=#a6b0a0
grey1=#939f91
grey2=#829181
statusline1=#93b259
statusline2=#708089
statusline3=#e66868
